#!/usr/bin/env python3
import argparse
import logging
from logger import setup_logging
from db_generation import generate_db


def main():
    parser = argparse.ArgumentParser(description="A sample script.")
    parser.add_argument('-chembl_db', type=str, help="Path of ChEMBL database (sqlite)")
    parser.add_argument('-arg2', type=str, help="Argument 2")
    args = parser.parse_args()
    generate_db.run_database_generation(args.chembl_db)

 
if __name__ == "__main__":
    setup_logging("generateDB_log", "DB_gen_errors.log")  # Set up once
    logger = logging.getLogger("generateDB_log")
    main()