#!/usr/bin/env python3
import argparse
import logging
from logger import setup_logging
from db_generation import generate_db


def argument_parser():
    parser = argparse.ArgumentParser(description="Database Generation Script")
    parser.add_argument('--min_actives', type=int, default=5, help="Minimum number of actives")
    parser.add_argument('--max_actives', type=int, default=100, help="Maximum number of actives")
    parser.add_argument('--threshold', type=float, default=0.4, help="Threshold for decoy selection")
    parser.add_argument('--min_decoys', type=int, default=5, help="Minimum number of decoys per active")
    parser.add_argument('--max_decoys', type=int, default=100, help="Maximum number of decoys per active")
    args = parser.parse_args()
    return args


def main():
    args = argument_parser()
    generate_db.run_database_generation(
        min_actives=args.min_actives,
        max_actives=args.max_actives,
        threshold=args.threshold,
        min_decoys=args.min_decoys,
        max_decoys=args.max_decoys)

 
if __name__ == "__main__":
    setup_logging("generateDB_log", "DB_gen_errors.log")  # Set up once
    logger = logging.getLogger("generateDB_log")
    main()